config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'help'        => 'static_pages#help'
  get     'about'       => 'static_pages#about'
  get     'contact'     => 'static_pages#contact'
  
  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy'
  
  get     'signup'      => 'users#new'
  resources :users, except: :new do
    member do
      get :feeds
    end
  end
  
  resources :feeds,             only: [:index, :show, :destroy] do
    resources :articles, only: [:index]
  end
  
  resources :articles, only: [:show] do
    resources :recordings, shallow: true
    member do
      post 'recordings/create_tts'
    end
  end

  resources :subscriptions,     only: [:create, :destroy]
  get     '/feeds/autocomplete' => "feeds#autocomplete"

  

end

app/models/recording.rb
class Recording < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  
  validates :article_id,    presence: true
  validates :uploaded_by,   presence: true

  has_attached_file :audiofile
  validates_attachment_presence :audiofile
  validates_attachment_content_type :audiofile, :content_type => [ 'audio/mpeg', 'audio/mp3', 'application/octet-stream' ],
                                    :message => 'file must be of filetype .mp3'
                                    
  before_save { self.audiofile_file_name = SecureRandom.hex(10) + self.audiofile_file_name }
                                    
end

app/controllers/recordings_controller.rb
require 'uri'
require 'open-uri'

class RecordingsController < ApplicationController
  include RecordingsHelper
 
def new
  @article = Article.find(params[:article_id])
  @recording = Recording.new
end
  
def create
  @article = Article.find(params[:article_id])
  @recording = @article.recordings.build(recording_params)
  @recording.uploaded_by = current_user.id
  @recording.uploaded_by_name = current_user.name
  if @recording.save
    flash[:success] = "Successfully added recording"
    redirect_to @recording
  else
    flash[:danger] = "Failed to save recording"
    get 'new'
  end
end

def create_tts
  @article = Article.find(params[:id])
  body = @article.body
  body = ActionController::Base.helpers.sanitize(body, :tags=>[])
  body = body.squish
  tts_text = URI.encode(body.to_str)
  tts_text = "http://tts-api.com/tts.mp3?q=#{tts_text}"
  @recording = @article.recordings.build(audiofile: URI.parse(tts_text))
  @recording.uploaded_by = tts_user.id
  @recording.uploaded_by_name = tts_user.name
  if @recording.save
    flash[:success] = "Successfully added recording"
    redirect_to @recording
  else
    flash[:danger] = "Failed to save recording"
    redirect_to :back
  end
end

def index
  @recordings = Recording.paginate(page: params[:page])
end

def show
  @recording = Recording.find(params[:id])
  @urlstring = @recording.audiofile.url # May be a coincidence, but audiojs doesn't find the url with erb. Send over as instance variable.
  @article_title = Article.find(@recording.article_id).title
  @uploaded_by = User.find(@recording.uploaded_by).name
end

def destroy
  Recording.find(params[:id]).destroy
  flash[:success] = "Recording deleted"
  redirect_to recordings_path
end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def recording_params
  params.require(:recording).permit(:audiofile)
end
  
end

app/helpers/recordings_helper.rb
module RecordingsHelper
  
  def tts_user
    @ttsuser = @ttsuser ? @ttsuser : User.find_by(name: "Generated TTS")
  end
  
end

app/views/recordings/_body.html.erb
<%= form_for [@article, @recording], :url => article_recordings_path(@article), :html => { :multipart => true } do |form| %>
  <%= form.file_field :audiofile, class: "filestyle", data: {buttonName: "btn-primary"}, :tabindex => '-1' %>
  <div class="bootstrap-filestyle input-group">
    <input type="text" class="form-control" disabled>
    <span class="group-span-filestyle input-group-btn" tabindex="0">
      <label for="recording_audiofile" class="btn btn_primary">
        <span class="glyphicon glyphicon-folder-open">
        </span> " Choose file"
      </label>
    </span>
  </div>
  <%= form.submit "Upload recording", class: "btn btn-primary" %>
<% end %>

app/views/recordings/_new_rec_modal.html.erb
<div class="modal fade" id="rec-modal" tabindex="-1" role="dialog" aria-labelledby="rec-modal_label" aria-hidden="true">
  <div class="modal-dialog rec-modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h3 class="rec-modal-title">
          
        </h3>
      </div>
      <div class="rec-modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/recordings/_recording.erb
<li>
  <%= link_to recording.audiofile_file_name, recording %>
  <%= audio_tag recording.audiofile.url, preload: "auto", controls: true %>
    <% if current_user.admin? %>
    | <%= link_to "delete", recording, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/recordings/index.html.erb
<% provide(:title, 'All recordings') %>
<h1>All recordings</h1>

<%= will_paginate %>

<ul class="recordings">
  <%= render @recordings %>
</ul>

<%= will_paginate %>

app/views/recordings/new.html.erb
<% provide(:title, 'Upload Recording') %>
<h1>Upload</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@article, @recording], :url => article_recordings_path(@article), :html => { :multipart => true } do |form| %>
      <%= form.file_field :audiofile, class: "filestyle", data: {buttonName: "btn-primary"} %>
      <%= form.submit "Upload recording", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/recordings/new.js.erb
$(".rec-modal-title").html("Upload Recording")
$(".rec-modal-body").html("<%= escape_javascript(render 'body') %>")
$("#rec-modal").modal('show')

app/views/recordings/show.html.erb
<script>
  audiojs.events.ready(function() {
    var as = audiojs.createAll();
  });
</script>

<audio src="<%= @urlstring %>" preload="auto"></audio>
<small>Recording of</small>  <%= link_to @article_title, article_path(id: @recording.article_id) %>
<small>Uploaded by</small>  <%= @uploaded_by %>