config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'help'        => 'static_pages#help'
  get     'about'       => 'static_pages#about'
  get     'contact'     => 'static_pages#contact'
  
  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy'
  
  get     'signup'      => 'users#new'
  resources :users, except: :new do
    member do
      get :feeds
    end
  end
  
  resources :feeds,             only: [:index, :show, :destroy] do
    resources :articles, only: [:index]
  end
  
  resources :articles, only: [:show] do
    resources :recordings, shallow: true
    member do
      post 'recordings/create_tts'
    end
  end

  resources :subscriptions,     only: [:create, :destroy]
  get     '/feeds/autocomplete' => "feeds#autocomplete"

  

end

app/models/article.rb
require 'rubygems'
require 'nokogiri'

class Article < ActiveRecord::Base
  belongs_to :feed
  has_many :recordings
  
  before_destroy :check_for_recordings
  
  validates :urlstring, presence: true
  validates :title,     presence: true
  validates :preview,   presence: true  
  validates :feed_id,   presence: true
  
  # Override getter for body
  def body
    if self[:body].nil?
      parse_html_for_body
    end
    self[:body]
  end
  
  private
  
    def parse_html_for_body
      page = Nokogiri::HTML(open(self.urlstring), nil, 'UTF-8')
      page.xpath("//script").remove
      page.xpath("//img").remove
      page.xpath("//comment()").remove
    
      parent_keys = Array.new
      paragraphs = page.css('p')
      paragraphs.each do |p|
        if !!p.parent['id']
          parent_keys.push('id---' + p.parent['id'])
        end
        if !!p.parent['class']
          parent_keys.push('class---' + p.parent['class'])
        end
        if !!p.parent['style']
          parent_keys.push('style---' + p.parent['style'])
        end
      end
    
      parent_keys = parent_keys.uniq
      
      max_p = 0
      max_k = ""
      parent_keys.each do |k|
        h = k.split('---')
        path = "//div[@" + h[0] + "=\"" + h[1] + "\"]"
        elements = page.xpath(path)
        elements.each do |e|
          if e.xpath('./p').count > max_p
            max_p = e.xpath('./p').count
            max_k = k
          end
        end
      end
    
      max_h = max_k.split('---')
      max_path = "//div[@" + max_h[0] + "=\"" + max_h[1] + "\"]"
      
      update_attribute(:body, page.xpath(max_path).to_html.valid_encoding? ? page.xpath(max_path) : 'Encoding error')
    end
    
    def check_for_recordings
      if self.recordings.count > 0
        errors.add_to_base("cannot delete article while recordings exist")
        return false
      end      
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @feed = Feed.find(params[:feed_id])
    @articles = @feed.articles
  end

  def show
    @article = Article.find(params[:id])
    @article.body # Initialize body content via model attribute getter override
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_body.html.erb
<div class="col-md-11 article-modal-body">
  <%= @article.body.html_safe %>
</div>

app/views/articles/_show_article_modal.html.erb
<div class="modal fade" id="article-modal" tabindex="-1" role="dialog" aria-labelledby="article-modal_label" aria-hidden="true">
  <div class="modal-dialog article-modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title">
          
        </h3>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/articles/_title.html.erb
<%= link_to @article.title, @article.urlstring, :target => "_blank" %>

app/views/articles/index.html.erb
<h1><%= @feed.title %></h1>
<table id="feeds" class="table table-striped">
  <thead>
    <tr>
      <th>Article</th>
      <th>Released</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |a| %>
      <tr data-item-id=<%= "#{a.id}" %>>
        <td>
          <h4><%= a.title %></h4>
          <%= a.preview.html_safe %>
          <div class="row text-right">
            <div class="btn-group" role="group" aria-label="...">
              <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                <%= link_to '<span class="glyphicon glyphicon-record"></span>'.html_safe, a, class: "btn-default" %>
              <% end %>
              <% buttonclass = a.recordings.empty? ? "btn btn-default" : "btn btn-default disabled" %>
              <%= button_tag(type: 'submit', class: buttonclass) do %>
                <%= link_to '<span class="glyphicon glyphicon-upload"></span>'.html_safe, new_article_recording_path(a), class: "btn-default" %>
              <% end %>
              <div class="btn-group">
                <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                  <%= link_to '<span class="glyphicon glyphicon-play"></span>'.html_safe, recordings_create_tts_article_path(a), method: :post, class: "btn-default" %>
                <% end %>                
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span class="caret"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>                
                <ul class="dropdown-menu" role="menu">
                  <% a.recordings.each do |r| %>
                    <li><%= link_to r.audiofile_file_name, r %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </td>
        <td><small>
          <% if !!(a.pubdate) %>
            Posted <%= time_ago_in_words(a.pubdate) %> ago.
          <% end %>
        </small></td>
      </tr> 
    <% end %>
  </tbody>
</table>

<%= render 'show_article_modal' %>
<%= render 'recordings/new_rec_modal' %>

<div class="btn-group">
  <button type="button" class="btn btn-danger">Action</button>
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div>

app/views/articles/show.html.erb
<h1><%= link_to @article.title, @article.urlstring, :target => "_blank" %></h1>
<%= @article.body.html_safe %>

app/views/articles/show.js.erb
$(".modal-title").html("<%= escape_javascript(render 'title') %>")
$(".modal-body").html("<%= escape_javascript(render 'body') %>")
$("#article-modal").modal('show')