config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'help'        => 'static_pages#help'
  get     'about'       => 'static_pages#about'
  get     'contact'     => 'static_pages#contact'
  
  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy'
  
  get     'signup'      => 'users#new'
  resources :users, except: :new do
    member do
      get :feeds
    end
  end
  
  resources :feeds,             only: [:index, :show, :destroy] do
    resources :articles, only: [:index]
  end
  
  resources :articles, only: [:show] do
    resources :recordings, shallow: true
    member do
      post 'recordings/create_tts'
    end
  end

  resources :subscriptions,     only: [:create, :destroy]
  get     '/feeds/autocomplete' => "feeds#autocomplete"

  

end

app/views/layouts/_feedpanel.html.erb
<aside class="col-md-3 sidebar">
  <section class="user_info">
    <%= render 'shared/user_info' %>
  </section>
  <section class="subscription_form">
    <%= render 'shared/subscription_form' %>
  </section> 
  <h4>BoT Recordings</h4>
  <ul class="nav nav-sidebar">
    <li><%= link_to "Placeholder", "#" %></li>
  </ul>
  <h4>Subscriptions</h4>
  <ul class="nav nav-sidebar">
    <% current_user.feeds.each do |f| %>
      <li <%= ("class= \"active\"") if ((!!@feed) && (f.id == @feed.id)) %>><%= link_to f.title, feed_articles_path(f) %></li>
    <% end %>
  </ul>
  <h4>Playlists</h4>
  <ul class="nav nav-sidebar">
    <li><%= link_to "Placeholder", "#" %></li>
  </ul>  
</aside>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Blogs on Tape proof of concept by Jay and Ross
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Blogs on Tape", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Feeds", feeds_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to '<span class="glyphicon glyphicon-user"></span> Profile'.html_safe, current_user %></li>
              <li><%= link_to '<span class="glyphicon glyphicon-cog"></span> Settings'.html_safe, edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to '<span class="glyphicon glyphicon-log-out"></span> Log Out'.html_safe, logout_path, method: "delete" %>
              </li>
            </ul>
          </li>        
        <% else %>
          <li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> Log In'.html_safe, login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_playerpanel.html.erb
    <script>
      $(function() { 
        // Setup the player to autoplay the next track
        var a = audiojs.createAll({
          trackEnded: function() {
            var next = $('ol li.playing').next();
            if (!next.length) next = $('ol li').first();
            next.addClass('playing').siblings().removeClass('playing');
            audio.load($('a', next).attr('data-src'));
            audio.play();
          }
        });
        
        // Load in the first track
        var audio = a[0];
            first = $('ol a').attr('data-src');
        $('ol li').first().addClass('playing');
        audio.load(first);

        // Load in a track on click
        $('ol li').click(function(e) {
          e.preventDefault();
          $(this).addClass('playing').siblings().removeClass('playing');
          audio.load($('a', this).attr('data-src'));
          audio.play();
        });
        // Keyboard shortcuts
        $(document).keydown(function(e) {
          var unicode = e.charCode ? e.charCode : e.keyCode;
             // right arrow
          if (unicode == 39) {
            var next = $('li.playing').next();
            if (!next.length) next = $('ol li').first();
            next.click();
            // back arrow
          } else if (unicode == 37) {
            var prev = $('li.playing').prev();
            if (!prev.length) prev = $('ol li').last();
            prev.click();
            // spacebar
          } else if (unicode == 32) {
            audio.playPause();
          }
        })
      });
    </script>

<div class="col-md-3">
    <div id="wrapper">
      <h4>wait what — notorious xx <em>(2009)</em></h4>
      <audio preload></audio>
      <ol>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/01-dead-wrong-intro.mp3">dead wrong intro</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/02-juicy-r.mp3">juicy-r</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/03-its-all-about-the-crystalizabeths.mp3">it's all about the crystalizabeths</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/04-islands-is-the-limit.mp3">islands is the limit</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/05-one-more-chance-for-a-heart-to-skip-a-beat.mp3">one more chance for a heart to skip a beat</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/06-suicidal-fantasy.mp3">suicidal fantasy</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/07-everyday-shelter.mp3">everyday shelter</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/08-basic-hypnosis.mp3">basic hypnosis</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/09-infinite-victory.mp3">infinite victory</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/10-the-curious-incident-of-big-poppa-in-the-nighttime.mp3">the curious incident of big poppa in the nighttime</a></li>
        <li><a href="#" data-src="http://kolber.github.io/audiojs/demos/mp3/11-mo-stars-mo-problems.mp3">mo stars mo problems</a></li>
      </ol>
    </div>
    <div id="shortcuts">
      <div>
        <h4>Keyboard shortcuts:</h4>
        <p><em>&rarr;</em> Next track</p>
        <p><em>&larr;</em> Previous track</p>
        <p><em>Space</em> Play/pause</p>
      </div>
    </div>
</div>   

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/columns.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <div class="row">
        <%= render 'layouts/feedpanel' %>
        <div class="col-md-6">
          <%= yield %>
        </div>
        <%= render 'layouts/playerpanel' %>
      </div>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>